# Generated by Django 5.1.7 on 2025-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionImpresionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Etiqueta 4x6 pulgadas', max_length=50)),
                ('ancho_pulgadas', models.FloatField(default=4.0)),
                ('alto_pulgadas', models.FloatField(default=6.0)),
            ],
        ),
    ]
