# Generated by Django 5.1.7 on 2025-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('tipo_bateria', models.CharField(choices=[('BAU', 'Batería Automotriz'), ('B6V', 'Baterías 6 Voltios')], max_length=3)),
                ('peso_lb', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('peso_neto_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_neto_lb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_bruto_lb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paletas', models.ManyToManyField(blank=True, to='paletas.paleta')),
            ],
        ),
    ]
