# Generated by Django 5.1.7 on 2025-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0002_configuracionimpresionetiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
