# Generated by Django 5.1.7 on 2025-04-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0003_historiallimpieza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='peso_kg',
            new_name='peso_bruto_kg',
        ),
        migrations.RenameField(
            model_name='paleta',
            old_name='peso_lb',
            new_name='peso_bruto_lb',
        ),
    ]
