# Generated by Django 5.1.7 on 2025-04-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0004_rename_peso_kg_paleta_peso_bruto_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paleta',
            name='cantidad_baterias',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
