# Generated by Django 5.2 on 2025-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0005_paleta_cantidad_baterias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleta',
            name='cantidad_baterias',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paleta',
            name='tipo_bateria',
            field=models.CharField(choices=[('BAU', 'Batería Automotriz'), ('B6V', 'Baterías 6 Voltios'), ('BI', 'Baterías Industriales'), ('MOT', 'Baterías para motocicleta')], max_length=3),
        ),
    ]
