# Generated by Django 5.2 on 2025-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0006_alter_paleta_cantidad_baterias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paleta',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
