# Generated by Django 5.2 on 2025-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0007_paleta_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleta',
            name='localidad',
            field=models.CharField(blank=True, choices=[('HAI', 'Haina'), ('HER', 'Herrera'), ('STGO', 'Santiago')], max_length=100, null=True),
        ),
    ]
